subtopicname0: "/scan"
pubtopicname0: "/scan_new"
subtopicname1: "/vertical_laser_2d"
pubtopicname1: "/vertical_laser_2d_cropped"
simulation: true
multechoflag: false
angle0: 160
angle1: 160
lidarnum: 1
