subtopicname0: "/scan"
pubtopicname0: "/scan_new"
subtopicname1: "/vertical_laser_2d"
pubtopicname1: "/vertical_laser_2d_cropped"
simulation: true
multechoflag: false
angle0: 240
angle1: 240
lidarnum: 1
